version: "3"
services:
  backend:
    build: .
    ports:
      - "3001:3001"
    env_file: ".env"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes: 
  redis:
    driver: local
