version: "3"
services:
  backend:
    build: .
    ports:
      - "3001:3001"
    env_file: ".env"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis:/data

volumes: 
  redis:
    driver: local
